const STUDIO_DATA: any = {
  rose: {
    name: "Premium Rose",
    colors: [
      { id: "red", name: "Ruby Red", hex: "#B91C1C" },
      { id: "yellow", name: "Bright Yellow", hex: "#FACC15" },
      { id: "pink", name: "Soft Pink", hex: "#F472B6" },
    ],
    images: {
      "5-red": [
        "/images/F/R/RR5/1.png",
        "/images/F/R/RR5/2.png",
        "/images/F/R/RR5/3.png",
        "/images/F/R/RR5/4.png",
        "/images/F/R/RR5/5.png",
      ],
      "6-red": [
        "/images/F/R/RR6/1.png",
        "/images/F/R/RR6/2.png",
        "/images/F/R/RR6/3.png",
        "/images/F/R/RR6/4.png",
        "/images/F/R/RR6/5.png",
      ],
      "7-red": [
        "/images/F/R/RR7/1.png",
        "/images/F/R/RR7/2.png",
        "/images/F/R/RR7/3.png",
        "/images/F/R/RR7/4.png",
        "/images/F/R/RR7/5.png",
      ],
      "8-red": [
        "/images/F/R/RR8/1.png",
        "/images/F/R/RR8/2.png",
        "/images/F/R/RR8/3.png",
        "/images/F/R/RR8/4.png",
        "/images/F/R/RR8/5.png",,
      ],
      "9-red": [
        "/images/F/R/RR9/1.png",
        "/images/F/R/RR9/2.png",
        "/images/F/R/RR9/3.png",
        "/images/F/R/RR9/4.png",
        "/images/F/R/RR9/5.png",
      ],
      "10-red": [
        "/images/F/R/RR10/1.png",
        "/images/F/R/RR10/2.png",
        "/images/F/R/RR10/3.png",
        "/images/F/R/RR10/4.png",
        "/images/F/R/RR10/5.png",
      ],
      "5-yellow": [
        "/images/F/R/RY5/1.png",
        "/images/F/R/RY5/2.png",
        "/images/F/R/RY5/3.png",
        "/images/F/R/RY5/4.png",
        "/images/F/R/RY5/5.png",
      ],
      "6-yellow": [
        "/images/F/R/RY6/1.png",
        "/images/F/R/RY6/2.png",
        "/images/F/R/RY6/3.png",
        "/images/F/R/RY6/4.png",
        "/images/F/R/RY6/5.png",
      ],
      "7-yellow": [
        "/images/F/R/RY7/1.png",
        "/images/F/R/RY7/2.png",
        "/images/F/R/RY7/3.png",
        "/images/F/R/RY7/4.png",
        "/images/F/R/RY7/5.png",
      ],
      "8-yellow": [
        "/images/F/R/RY8/1.png",
        "/images/F/R/RY8/2.png",
        "/images/F/R/RY8/3.png",
        "/images/F/R/RY8/4.png",
        "/images/F/R/RY8/5.png",
      ],
      "9-yellow": [
        "/images/F/R/RY9/1.png",
        "/images/F/R/RY9/2.png",
        "/images/F/R/RY9/3.png",
        "/images/F/R/RY9/4.png",
        "/images/F/R/RY9/5.png",
      ],
      "10-yellow": [
        "/images/F/R/RY10/1.png",
        "/images/F/R/RY10/2.png",
        "/images/F/R/RY10/3.png",
        "/images/F/R/RY10/4.png",
        "/images/F/R/RY10/5.png",
      ],
      "5-pink": [
        "/images/F/R/RP5/1.png",
        "/images/F/R/RP5/2.png",
        "/images/F/R/RP5/3.png",
        "/images/F/R/RP5/4.png",
        "/images/F/R/RP5/5.png",
      ],
      "6-pink": [
        "/images/F/R/RP6/1.png",
        "/images/F/R/RP6/2.png",
        "/images/F/R/RP6/3.png",
        "/images/F/R/RP6/4.png",
        "/images/F/R/RP6/5.png",
      ],
      "7-pink": [
        "/images/F/R/RP7/1.png",
        "/images/F/R/RP7/2.png",
        "/images/F/R/RP7/3.png",
        "/images/F/R/RP7/4.png",
        "/images/F/R/RP7/5.png",
      ],
      "8-pink": [
        "/images/F/R/RP8/1.png",
        "/images/F/R/RP8/2.png",
        "/images/F/R/RP8/3.png",
        "/images/F/R/RP8/4.png",
        "/images/F/R/RP8/5.png",
      ],
      "9-pink": [
        "/images/F/R/RP9/1.png",
        "/images/F/R/RP9/2.png",
        "/images/F/R/RP9/3.png",
        "/images/F/R/RP9/4.png",
        "/images/F/R/RP9/5.png",
      ],
      "10-pink": [
        "/images/F/R/RP10/1.png",
        "/images/F/R/RP10/2.png",
        "/images/F/R/RP10/3.png",
        "/images/F/R/RP10/4.png",
        "/images/F/R/RP10/5.png",
      ],

      
    }
  },
  lily: {
    name: "Elegant Lily",
    colors: [
      { id: "white", name: "Pure White", hex: "#F8FAFC" },
      { id: "pink", name: "Deep Maroon", hex: "#c746ad" },
      { id: "red", name: "White Pink Mix", hex: "#d71442" },
    ],
    images: {
      "5-white": [
        "/images/F/L/LW5/1.png",
        "/images/F/L/LW5/2.png",
        "/images/F/L/LW5/3.png",
        "/images/F/L/LW5/4.png",
        "/images/F/L/LW5/5.png", 
      ],
      "6-white": [
        "/images/F/L/LW6/1.png",
        "/images/F/L/LW6/2.png",
        "/images/F/L/LW6/3.png",
        "/images/F/L/LW6/4.png",
        "/images/F/L/LW6/5.png", 
      ],
      "7-white": [
        "/images/F/L/LW7/1.png",
        "/images/F/L/LW7/2.png",
        "/images/F/L/LW7/3.png",
        "/images/F/L/LW7/4.png",
        "/images/F/L/LW7/5.png", 
      ],
      "8-white": [
        "/images/F/L/LW8/1.png",
        "/images/F/L/LW8/2.png",
        "/images/F/L/LW8/3.png",
        "/images/F/L/LW8/4.png",
        "/images/F/L/LW8/5.png", 
      ],
      "9-white": [
        "/images/F/L/LW9/1.png",
        "/images/F/L/LW9/2.png",
        "/images/F/L/LW9/3.png",
        "/images/F/L/LW9/4.png",
        "/images/F/L/LW9/5.png", 
      ],
      "10-white": [
        "/images/F/L/LW10/1.png",
        "/images/F/L/LW10/2.png",
        "/images/F/L/LW10/3.png",
        "/images/F/L/LW10/4.png",
        "/images/F/L/LW10/5.png", 
      ],
      "5-pink": [
        "/images/F/L/LP5/1.png",
        "/images/F/L/LP5/2.png",
        "/images/F/L/LP5/3.png",
        "/images/F/L/LP5/4.png",
        "/images/F/L/LP5/5.png", 
      ],
      "6-pink": [
        "/images/F/L/LP6/1.png",
        "/images/F/L/LP6/2.png",
        "/images/F/L/LP6/3.png",
        "/images/F/L/LP6/4.png",
        "/images/F/L/LP6/5.png", 
      ],
      "7-pink": [
        "/images/F/L/LW7/1.png",
        "/images/F/L/LW7/2.png",
        "/images/F/L/LW7/3.png",
        "/images/F/L/LW7/4.png",
        "/images/F/L/LW7/5.png", 
      ],
      "8-pink": [
        "/images/F/L/LW8/1.png",
        "/images/F/L/LW8/2.png",
        "/images/F/L/LW8/3.png",
        "/images/F/L/LW8/4.png",
        "/images/F/L/LW8/5.png", 
      ],
      "9-pink": [
        "/images/F/L/LW9/1.png",
        "/images/F/L/LW9/2.png",
        "/images/F/L/LW9/3.png",
        "/images/F/L/LW9/4.png",
        "/images/F/L/LW9/5.png", 
      ],
      "10-pink": [
        "/images/F/L/LW10/1.png",
        "/images/F/L/LW10/2.png",
        "/images/F/L/LW10/3.png",
        "/images/F/L/LW10/4.png",
        "/images/F/L/LW10/5.png", 
      ],
      "5-red": [
        "/images/F/L/LR5/1.png",
        "/images/F/L/LR5/2.png",
        "/images/F/L/LR5/3.png",
        "/images/F/L/LR5/4.png",
        "/images/F/L/LR5/5.png",
        
      ],
      "6-red": [
        "/images/F/L/LR6/1.png",
        "/images/F/L/LR6/2.png",
        "/images/F/L/LR6/3.png",
        "/images/F/L/LR6/4.png",
        "/images/F/L/LR6/5.png",
      ],
      "7-red": [
        "/images/F/L/LR7/1.png",
        "/images/F/L/LR7/2.png",
        "/images/F/L/LR7/3.png",
        "/images/F/L/LR7/4.png",
        "/images/F/L/LR7/5.png",
      ],
      "8-red": [
        "/images/F/L/LR8/1.png",
        "/images/F/L/LR8/2.png",
        "/images/F/L/LR8/3.png",
        "/images/F/L/LR8/4.png",
        "/images/F/L/LR8/5.png",
      ],
      "9-red": [
        "/images/F/L/LR9/1.png",
        "/images/F/L/LR8/2.png",
        "/images/F/L/LR9/3.png",
        "/images/F/L/LR9/4.png",
        "/images/F/L/LR9/5.png",
      ],
      "10-red": [
        "/images/F/L/LR10/1.png",
        "/images/F/L/LR10/2.png",
        "/images/F/L/LR10/3.png",
        "/images/F/L/LR10/4.png",
        "/images/F/L/LR10/5.png",
      ],
    }
  },
  lotus: {
    name: "Sacred Lotus",
    colors: [
      { id: "pink", name: "Lotus Pink", hex: "#FBCFE8" },
      { id: "white", name: "Sacred White", hex: "#FFFFFF" },
      { id: "purple", name: "Purple Lotus", hex: "#e95dc3" },
    ],
    images: {
      "5-pink": [
        "/images/F/Lo/lp5/1.png",
        "/images/F/Lo/lp5/2.png",
        "/images/F/Lo/lp5/3.png",
        "/images/F/Lo/lp5/4.png",
        "/images/F/Lo/lp5/5.png",
      ],
      "6-pink": [
        "/images/F/Lo/lp6/1.png",
        "/images/F/Lo/lp6/2.png",
        "/images/F/Lo/lp6/3.png",
        "/images/F/Lo/lp6/4.png",
        "/images/F/Lo/lp6/5.png",
      ],
      "7-pink": [
        "/images/F/Lo/lp7/1.png",
        "/images/F/Lo/lp7/2.png",
        "/images/F/Lo/lp7/3.png",
        "/images/F/Lo/lp7/4.png",
        "/images/F/Lo/lp7/5.png",
      ],
      "8-pink": [
        "/images/F/Lo/lp8/1.png",
        "/images/F/Lo/lp8/2.png",
        "/images/F/Lo/lp8/3.png",
        "/images/F/Lo/lp8/4.png",
        "/images/F/Lo/lp8/5.png",
      ],
      "9-pink": [
        "/images/F/Lo/lp9/1.png",
        "/images/F/Lo/lp9/2.png",
        "/images/F/Lo/lp9/3.png",
        "/images/F/Lo/lp9/4.png",
        "/images/F/Lo/lp9/5.png",
      ],
      "10-pink": [
        "/images/F/Lo/lp10/1.png",
        "/images/F/Lo/lp10/2.png",
        "/images/F/Lo/lp10/3.png",
        "/images/F/Lo/lp10/4.png",
        "/images/F/Lo/lp10/5.png"
      ],
      "5-white": [
        "/images/F/Lo/lw5/1.png",
        "/images/F/Lo/lw5/2.png",
        "/images/F/Lo/lw5/3.png",
        "/images/F/Lo/lw5/4.png",
        "/images/F/Lo/lw5/5.png",
      ],
      "6-white": [
       "/images/F/Lo/lw6/1.png",
        "/images/F/Lo/lw6/2.png",
        "/images/F/Lo/lw6/3.png",
        "/images/F/Lo/lw6/4.png",
        "/images/F/Lo/lw6/5.png",
      ],
      "7-white": [
        "/images/F/Lo/lw7/1.png",
        "/images/F/Lo/lw7/2.png",
        "/images/F/Lo/lw7/3.png",
        "/images/F/Lo/lw7/4.png",
        "/images/F/Lo/lw7/5.png",
      ],
      "8-white": [
        "/images/F/Lo/lw8/1.png",
        "/images/F/Lo/lw8/2.png",
        "/images/F/Lo/lw8/3.png",
        "/images/F/Lo/lw8/4.png",
        "/images/F/Lo/lw8/5.png",
      ],
      "9-white": [
        "/images/F/Lo/lw9/1.png",
        "/images/F/Lo/lw9/2.png",
        "/images/F/Lo/lw9/3.png",
        "/images/F/Lo/lw9/4.png",
        "/images/F/Lo/lw9/5.png",
      ],
      "10-white": [
        "/images/F/Lo/lw10/1.png",
        "/images/F/Lo/lw10/2.png",
        "/images/F/Lo/lw10/3.png",
        "/images/F/Lo/lw10/4.png",
        "/images/F/Lo/lw10/5.png",
      ],
      "5-purple": [
        "/images/F/Lo/pl5/1.png",
        "/images/F/Lo/pl5/2.png",
        "/images/F/Lo/pl5/3.png",
        "/images/F/Lo/pl5/4.png",
        "/images/F/Lo/pl5/5.png",
      ],
      "6-purple": [
        "/images/F/Lo/pl6/1.png",
        "/images/F/Lo/pl6/2.png",
        "/images/F/Lo/pl6/3.png",
        "/images/F/Lo/pl6/4.png",
        "/images/F/Lo/pl6/5.png",
      ],
      "7-purple": [
        "/images/F/Lo/pl7/1.png",
        "/images/F/Lo/pl7/2.png",
        "/images/F/Lo/pl7/3.png",
        "/images/F/Lo/pl7/4.png",
        "/images/F/Lo/pl7/5.png",
      ],
      "8-purple": [
        "/images/F/Lo/pl8/1.png",
        "/images/F/Lo/pl8/2.png",
        "/images/F/Lo/pl8/3.png",
        "/images/F/Lo/pl8/4.png",
        "/images/F/Lo/pl8/5.png",
      ],
      "9-purple": [
        "/images/F/Lo/pl9/1.png",
        "/images/F/Lo/pl9/2.png",
        "/images/F/Lo/pl9/3.png",
        "/images/F/Lo/pl9/4.png",
        "/images/F/Lo/pl9/5.png",
      ],
      "10-purple": [
        "/images/F/Lo/pl10/1.png",
        "/images/F/Lo/pl10/2.png",
        "/images/F/Lo/pl10/3.png",
        "/images/F/Lo/pl10/4.png",
        "/images/F/Lo/pl10/5.png",
      ],

    
    }
  }
};